### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by simonmysun** [Brutuski/tmux-ticker#4]
Hi,

thanks for the plug-in. I installed and configured it following the instructions, but nothing has shown up. I set my `status-left` to `tik#{ticker_dji}~#{ticker_dji_change}tik` and it turns out to be `tik~tik` with no error message. 

How can I access more information of the plug-in? such as log, etc.

It's maybe because of the proxy issue. but I'm not sure. 

Thx

**Comment by Brutuski** [comment]
Hey,

sucks you are having trouble with it, let's try and figure it out together.

> I installed and configured it following the instructions, but nothing has shown up.

What method did you choose to install it? Manual? TPM?

> I set my status-left to tik#{ticker_dji}~#{ticker_dji_change}tik and it turns out to be tik~tik with no error message.

I just tried that exact thing, worked properly for me. The script would only throw out an error-message if you had no internet.

> How can I access more information of the plug-in? such as log, etc.

I wrote this plugin to be as simple as possible, no logging etc available as of right now sadly.

What OS are you running?

Run this in your terminal `curl -V`. It should show you the version of `curl` installed on your system

Try and just run this command in your terminal and see if you get an output

`curl -s https://www.marketwatch.com/investing/index/djia | grep '<meta name="price" content="' | cut -d'"' -f4`

**Comment by simonmysun** [comment]
Hi Brutuski,

I installed via TPM. I'm not 100% sure it is installed but since other plug-ins are successfully installed, TPM should be working. 

I believe your plug-in has no problem and it should be somewhere wrong in my case. 

> `curl -s https://www.marketwatch.com/investing/index/djia | grep '<meta name="price" content="' | cut -d'"' -f4`

This command has correct output here. I can even put this into my status bar configuration directly with `#()` and it also works.

**Comment by Brutuski** [comment]
Hey,

> I installed via TPM. I'm not 100% sure it is installed but since other plug-ins are successfully installed, TPM should be working.

TPM makes things easy for sure. Let's try to uninstall and install it again. Uninstalling instructions are [here](https://github.com/tmux-plugins/tpm#uninstalling-plugins)

> This command has correct output here. I can even put this into my status bar configuration directly with #() and it also works.

Then it has to be some sort of an installation issue, since it's working fine for you otherwise.

Perhaps try to install it manually and check.
