### ISSUE TITLE
Get value of ticker_stock_change to use for conditional style

### ISSUE THREAD

**Issue by rphuber** [Brutuski/tmux-ticker#5]
I'd love to have a way to get the value of the change to find out if it's positive or negative so I could use the info to style the ticker price color.  Is this possible currently?  I have tried using `#{?ticker_stock_price>0}` but that doesn't seem to actually work.  is there a variable that I can use to determine the change direction?  Thanks for the great plugin

**Comment by rphuber** [comment]
I figured out a way to do this.  Is this something you would be interested in me adding to the package?

**Comment by Brutuski** [comment]
> Thanks for the great plugin

Thank you so much for the kind words.

> I figured out a way to do this. Is this something you would be interested in me adding to the package?

Sure thing man, go ahead and submit a PR. I will merge it asap.
If you can though, do post an image or 2 showing the functionality.

**Comment by rphuber** [comment]
Let me know your thoughts on this approach.
